# Generated by Django 2.1.5 on 2019-02-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_auto_20190217_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='gender',
        ),
        migrations.AlterField(
            model_name='students',
            name='exam_grade',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
