# Generated by Django 2.1.5 on 2019-02-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_auto_20190218_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='gender',
            field=models.CharField(choices=[('NONE', 'Choose one'), ('MALE', 'Male'), ('FEMALE', 'Female')], default='NONE', max_length=6),
        ),
    ]
